const axios = require("axios");
const PhoneOtp = require("../models/PhoneOtp");

// ==========================================================
// Message Central Client
// ==========================================================

const messageCentral = axios.create({
  baseURL: "https://cpaas.messagecentral.com",
  timeout: 30000,
  headers: {
    "Content-Type": "application/json",
    Accept: "application/json",
    authToken: process.env.MESSAGE_CENTRAL_AUTH_TOKEN,
  },
});

// ==========================================================
// Generate 6 Digit OTP
// ==========================================================

const generateOtp = () => {
  return Math.floor(100000 + Math.random() * 900000).toString();
};

// ==========================================================
// Send SMS using Message Central
// ==========================================================

const sendSms = async (phone, otp) => {
  try {
    const mobile = phone.replace("+", "");

    // ------------------------------------------------------------------
    // Replace this endpoint and payload with the exact one from
    // Message Central's API documentation.
    // ------------------------------------------------------------------

    const response = await messageCentral.post(
      "/verification/v3/send",
      {
        customerId: process.env.MESSAGE_CENTRAL_CUSTOMER_ID,
        countryCode: process.env.MESSAGE_CENTRAL_COUNTRY,
        mobileNumber: mobile,
        flowType: "SMS",

        // Custom OTP generated by backend
        otp,

        // Optional message template
        message: `Your AiTradeX OTP is ${otp}. It is valid for 5 minutes.`,
      }
    );

    console.log("========== MESSAGE CENTRAL ==========");
    console.log(response.data);

    return response.data;
  } catch (error) {
    console.error("MESSAGE CENTRAL ERROR");

    if (error.response) {
      console.error(error.response.data);
      throw new Error(
        error.response.data.message || "Failed to send SMS."
      );
    }

    throw error;
  }
};

// ==========================================================
// SEND PHONE OTP
// ==========================================================

const sendPhoneOtp = async (phone, purpose = "signup") => {
  try {
    phone = String(phone).trim();

    if (!phone) {
      throw new Error("Phone number is required.");
    }

    console.log("====================================");
    console.log("SEND PHONE OTP");
    console.log("Phone   :", phone);
    console.log("Purpose :", purpose);

    // Delete previous OTP
    await PhoneOtp.deleteMany({ phone });

    const otp = generateOtp();

    const expiresAt = new Date(Date.now() + 5 * 60 * 1000);

    const otpDoc = await PhoneOtp.create({
      phone,
      otp,
      verified: false,
      expiresAt,
    });

    console.log("OTP SAVED");
    console.log("OTP:", otp);

    // Send SMS
    await sendSms(phone, otp);

    return {
      success: true,
      otp,
      expiresAt: otpDoc.expiresAt,
    };
  } catch (error) {
    console.error("SEND PHONE OTP ERROR");
    console.error(error);

    throw error;
  }
};

// ==========================================================
// VERIFY PHONE OTP
// ==========================================================

const verifyPhoneOtp = async (phone, otp) => {
  try {
    phone = String(phone).trim();
    otp = String(otp).trim();

    console.log("====================================");
    console.log("VERIFY PHONE OTP");
    console.log("Phone :", phone);
    console.log("OTP   :", otp);

    const otpDoc = await PhoneOtp.findOne({
      phone,
      verified: false,
    }).sort({ createdAt: -1 });

    if (!otpDoc) {
      throw new Error("OTP not found.");
    }

    if (new Date() > otpDoc.expiresAt) {
      await PhoneOtp.deleteOne({
        _id: otpDoc._id,
      });

      throw new Error("OTP expired.");
    }

    if (String(otpDoc.otp) !== otp) {
      throw new Error("Invalid OTP.");
    }

    otpDoc.verified = true;

    await otpDoc.save();

    await PhoneOtp.deleteOne({
      _id: otpDoc._id,
    });

    return {
      success: true,
      verified: true,
      message: "Phone verified successfully.",
    };
  } catch (error) {
    console.error("VERIFY PHONE OTP ERROR");
    console.error(error);

    throw error;
  }
};

// ==========================================================

module.exports = {
  sendPhoneOtp,
  verifyPhoneOtp,
};